### ISSUE TITLE
How feasible would it be for a Redhat based port to be created?

### ISSUE THREAD

**Issue by rkwesk** [ltsp/community#16] opened 2019-09-08 10:56 UTC
It is my opinion that many users of a Redhat based distro would benefit from this amazing work. I have reached out to someone who has written some documentation for Fedora on ltsp two or three years ago, telling him about this wonderful ltsp19!

Why not share such a gem with as many more people as possible was my thinking.

Richard

**Comment by enaut** [comment] 2019-09-08 11:06
I would welcome that too.

I think so far it's just missing time, funding or volunteering to do a port.

To be included in the official Fedora repos there would need to be some style changes as ltsp19 does many things differently than the way Fedora advises to do them.

It might be better to fork ltsp or rather to redo the necessary steps in a rpm-distro-fashion.

Also ltsp is targeted mostly to schools. Teachers at schools typically use ubuntu - because "that is already hard enough".

just my opinion on the topic ;)

**Comment by alkisg** [comment] 2019-09-08 16:10
> I think so far it's just missing time, funding or volunteering to do a port.

True; personally since neither me nor my schools use rpm-based distributions, I'd need to find some funding to work on that.

> To be included in the official Fedora repos there would need to be some style changes as ltsp19 does many things differently than the way Fedora advises to do them. It might be better to fork ltsp or rather to redo the necessary steps in a rpm-distro-fashion.

Any developers would be welcomed to join the LTSP team, with or without Fedora experience.
I believe the LTSP code can be adjusted to be compliant with all distribution policies. For example, I was careful while designing its architecture so that it would work both when sent over TFTP (ltsp.img) and when provided locally (initramfs-tools or dracut).
Forking a project with low development power isn't really a good approach, as it leads to less maintained forks.

Additionally, I think the new LTSP architecture results in a lot less distro-specific code, compared to LTSP5.

**Comment by rkwesk** [comment] 2019-09-10 06:29
Yes, many choose Ubuntu for the reason you stated. In my opinion ltsp is worthwhile for many time constrained organizations (including but not only schools) and many of these already use a Redhat based system.

Alki, I also have the feeling that this latest code is less dependent on Debian based setups and I hope others elsewhere become aware and will recognize how useful and (relatively) easy it would be to work on such ports. Alas, my skills do not measure up.

Richard

**Comment by rkwesk** [comment] 2019-10-25 11:26
I was searching the net for active ltsp people with rpm distros and came across this discussion in:

     https://fedoramagazine.org/how-to-build-a-netboot-server-part-1/

I know that a netboot server is not the same but some of the comments suggested that those people would/could contribute if they were made aware of ltsp19. I emailed the two whose name had links but often email from unknowns go straight in to spam.  :((

This weekend I will try Fedora 30 and simply try to compile the source file of ltsp19 and see what happens.

Richard

**Comment by alkisg** [comment] 2019-10-25 12:31
LTSP19 is a netboot (fat client) server, not a terminal (thin client) server. The author of the blog you linked says he wants to do a part-2, with writable home; which is what LTSP already offers, along with lots more.
That probably means that the author there would love to have the new LTSP on Fedora.

Users testing LTSP on Fedora now won't be able to get it running, nor will they be able to give valuable feedback. A developer is needed:

The part of the Fedora port that will take the most time is dracut integration. After that is done, all initramfs-tools (.deb) and dracut (.rpm) based distributions will be very easy to support. Dracut does support the nfs=server:/path syntax that ipxe already has, so that we can have distro-agnostic command lines, but it does need the appropriate hooks to call the ltsp-bottom applet.

**Comment by rkwesk** [comment] 2019-10-26 12:32
Alright. However, I did an install of Fedora 30 but cannot get epoptes. I thought you should be aware of this also.

     Running transaction
     Preparing        :                                                            1/1 
     Running scriptlet: epoptes-client-0.5.10-4.1.noarch                           1/1 
     /var/tmp/rpm-tmp.ctsTeR: line 1: fg: no job control
     error: %prein(epoptes-client-0.5.10-4.1.noarch) scriptlet failed, exit status 1

     Error in PREIN scriptlet in rpm package epoptes-client
     Verifying        : epoptes-client-0.5.10-4.1.noarch                           1/1 

     Failed:
     epoptes-client-0.5.10-4.1.noarch

     Problem: conflicting requests
     - nothing provides python-pycha needed by epoptes-0.5.10-4.1.noarch
     =======================================================================
     Package         Architecture   Version              Repository                Size
     =======================================================================
     Skipping packages with broken dependencies:
     epoptes         noarch         0.5.10-4.1           rpmsphere-noarch         258 k

     Transaction Summary
     =======================================================================
     Skip  1 Package

     Nothing to do.

Richard

**Comment by alkisg** [comment] 2019-10-26 13:31
Richard I've never installed or tested Epoptes in Fedora; if you want to run it there, you should probably check who was the maintainer, and see if he's still interested in maintaining it.

Deb files do have a maintainer email address; maybe Fedora .rpm files also have that information.

It happens that Epoptes upstream developers are also Debian maintainers; but we don't maintain any other distributions; bug reports for them are to be filed downstream.

**Comment by enaut** [comment] 2019-10-28 20:16
@rkwesk I don't see epoptes in the repository (F31) where did you get an rpm? I'd suggest to compile it from source instead.
The problem is that python-pycha has either been renamed or your rpm-file is for a different distribution having a package named that way.

**Comment by alkisg** [comment] 2019-10-28 20:33
Epoptes 0.5.x was based on Python 2;
Epoptes 1.x is based on Python 3 and doesn't use pycha at all.

If anyone tries to get Epoptes running in a recent Fedora, I'd suggest they'd try with 1.x.

**Comment by kimheino** [comment] 2019-10-30 11:20
I'll copy-paste my mailing list message here:

```
I've ported ltsp 5 to rhel 7 and using it on various production
environments. Source repositories are available at launchpad.

I'm also going to port ltsp 19 to rhel 8, but it will take some time.
Probably early next year? I will do that alone if needed, but of course
all the help is welcome.
```

Launchpad = https://code.launchpad.net/ltsp

**Comment by rkwesk** [comment] 2019-10-31 10:21
The author responds:

Richard Kweskin <rkwesk@yahoo.com>
To:gbartho@siue.edu
Oct 24 at 5:05 PM
Hi Greg

I am not a part of the development team of ltsp here in Greece but have implemented their latest version called ltsp19 - 19 is for the year of conception - which is a total rewrite of ltsp (now called ltsp5.)

It works much easier with uefi and the code is much neater. I am hopeful that I can get a discussion going on an rpm port as the Greek team has concentrated on Debian's deb.

Have a look:

https://github.com/ltsp/


Richard Kweskin
retired IT



Bartholomew, Gregory <gbartho@siue.edu>
To:rkwesk@yahoo.com
Oct 28 at 2:35 PM
Hi Richard:

It is great to see that someone is reviving the LTSP! It is something that I would like to up on some of my systems at some point. Unfortunately, I'm a bit busy with some other projects right now.

An RPM for LTSP would be awesome! I'm not a package maintainer though. Have you seen Ankur's articles on maintaining RPMs?:
https://fedoramagazine.org/author/ankursinha/

Good luck with your project. Sorry that I don't have the time to help out right now.

Greg Bartholomew

**Comment by rkwesk** [comment] 2019-10-31 10:33
Without knowing Fedora 31 was being released I installed version 30 and found nfs and dnsmasq already installed. I tried to install epoptes and found that once I installed an rpm called sphere it gave me both epoptes and epoptes-client. However, their versions were 0.5 and so I came aground with psycha.

Searching Fedora packages for in https://pkgs.org/download/epoptes did not list Fedora 31 or epoptes 1.0.

Richard

**Comment by alkisg** [comment] 2019-10-31 10:39
Richard for Epoptes it would probably be better to use Epoptes issues, not LTSP issues.

Some more information regarding LTSP on RHEL.

The most difficult part would be the dracut (initramfs) integration. I've played with it a bit in the summer with partial success but I would need a couple of weeks of studying in order to things properly.
Someone with experience in dracut would do it much faster, but he'd have to spend some time to learn the new LTSP code base.

I'm willing to help such a person. If Kim's that person, I hope we'll be able to find some common free time to do this together.

After dracut integration is done, the rest of the things will be very easy. Maybe the only needed change will be in PAM integration (a couple of sed commands) and nothing more.

**Closed** 2020-10-16 17:41 UTC
Labels: question
