### ISSUE TITLE
Diskless or Thin clients? 

### ISSUE THREAD

**Issue by crazy-logic** [ltsp/community#155] opened 2020-09-02 20:43 UTC
So in the readme it seems like LTSP is now a diskless client project rather than a true thin client project - is that the case? I have installed a LTSP server and got it to the client can get to login stage but it appears not to be a true thin client - is that the case?

**Comment by alkisg** [comment] 2020-09-03 04:06
Hi, this is a duplicate of https://github.com/ltsp/community/issues/32, read that one and if you still have questions let's continue there.

**Closed** 2020-10-16 18:17 UTC
Labels: question
